In [1]:

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVR
from sklearn.metrics import r2_score,mean_squared_error
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('LE&QR.csv')
df.head()

J  D2-D1 ENERGY GAP  LOCAL-EXCITON RESONANCE  FREQUENCY  SIGMA     A_1PS
0  50               100               120.710678        400   0.01  0.002760
1  50               200               211.803399        400   0.01  0.012789
2  50               300               308.113883        400   0.01  0.156912
3  50               400               406.155281        400   0.01  0.560678
4  50               500               504.950976        400   0.01  0.074665

In [3]:
x = df.iloc[:,2:5]
y = df.iloc[:,5:6]
x;

In [4]:
y;

Machine Learning Algorithm

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size = 0.5, random_state = 0)

In [6]:
X_train;

In [7]:
y_train;

In [8]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_y = StandardScaler()
X_train = sc_X.fit_transform(X_train)
y_train = sc_y.fit_transform(y_train)

In [9]:
x1 = sc_X.fit_transform(x)
y1 = sc_y.fit_transform(y)
from sklearn.model_selection import cross_val_score
from sklearn.svm import SVR
regressor = SVR(kernel='rbf')
scores = cross_val_score(regressor, x1,y1, cv=5)
scores

/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return

array([0.82534586, 0.97432311, 0.91297102, 0.97208138, 0.82653766])

In [10]:
y1

array([[-1.44504677],
       [-1.38935809],
       [-0.58906899],
       ...,
       [-1.27998884],
       [-0.83053846],
       [ 1.37152863]])

In [11]:
X_train

array([[-1.27115562,  1.59058539,  0.91569426],
       [-0.16186737, -0.63233413, -1.09615907],
       [-2.00733539,  0.6379056 ,  1.64727728],
       ...,
       [ 0.83244245, -0.31477419,  0.54990274],
       [ 0.79467588, -1.58501392, -1.09615907],
       [ 0.027307  ,  0.32034567, -0.18168029]])

In [12]:
y_train

array([[-1.22042678],
       [ 1.22539151],
       [-1.4483829 ],
       ...,
       [-0.9075916 ],
       [-1.45410252],
       [ 1.74565353]])

In [13]:
from sklearn.svm import SVR
regressor = SVR(kernel ='rbf')
regressor.fit(X_train,y_train)

/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


SVR()

In [14]:
y_pred = sc_y.inverse_transform(regressor.predict(sc_X.transform(X_test)))
y_pred

array([0.30538467, 0.49771503, 0.34940615, ..., 0.50611795, 0.39147327,
       0.36144488])

In [15]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.9046212879322286

Try new models

In [16]:
X_try = [[750,800,0.01]];
y_try = sc_y.inverse_transform(regressor.predict(sc_X.transform(X_try)));
y_try

array([0.46665396])

In [17]:
X_try = [[100,800,0.01]];
y_try = sc_y.inverse_transform(regressor.predict(sc_X.transform(X_try)));
y_try

array([0.01354768])

In [18]:
X_try = [[100,200,0.01]];
y_try = sc_y.inverse_transform(regressor.predict(sc_X.transform(X_try)));
y_try

array([0.11711611])

In [19]:
X_try = [[100,200,0.1]];
y_try = sc_y.inverse_transform(regressor.predict(sc_X.transform(X_try)));
y_try

array([0.17042735])